### ISSUE TITLE
Allow changing the default 'outfmt' for different diagram types

### ISSUE THREAD

**Issue by priiduonu** [hertogp/imagine#1]
For example - setting `outfmt = 'pdf'` gives much better results for `blockdiag` diagrams when using pandoc for PDF output. There are probably other packages supporting PDF output as well (`graphviz`?). Maybe you could make the desired output format configurable or enable setting it in the code block arguments?

**Comment by nicoulaj** [comment]
That would be nice, for instance, I would like to use the SVG format for blockdiag.
