### ISSUE TITLE
is python2 required ?

### ISSUE THREAD

**Issue by m040601** [hertogp/imagine#14]
I just want to confirm that python2 is not required by imagine itself.

I am checking the installation of imagine on Archlinux using this package,
https://aur.archlinux.org/packages/python-pandoc-imagine

It wants to pull these dependencies
python2 (pypy19, stackless-python2) (make)

**Comment by hertogp** [comment]
No, imagine works with both python2.7+ and python3.
Imagine does have a dependency on 'pandocfilters'.

**Comment by hertogp** [comment]
Oh, and on 'six'
