### ISSUE TITLE
mermaid cli has moved

### ISSUE THREAD

**Issue by andreacassioli** [hertogp/imagine#4]
According to

https://mermaidjs.github.io/mermaidCLI.html

the mermaid cli is now maintained at

https://github.com/mermaidjs/mermaid.cli

The cli is now named `mmdc` and has a different syntax. It seems pandoc-imagine is not working with mermaid right now.

**Comment by priiduonu** [comment]
Solved by https://github.com/hertogp/imagine/pull/5
