### ISSUE TITLE
Generate images relative to output file, not current working directory

### ISSUE THREAD

**Issue by npryce** [hertogp/imagine#7]
At the moment, the images are generated in a pd-images subdirectory of the current working directory.  This means that image links in generated files are broken if the files are generated into a different directory. It also means that generated files end up in the top-level source directory.

Could pandoc-imagine generate image files relative to the output file instead?

E.g. if converting a markdown file `docs/example.md` to an HTML file `out/html/example.html`, I'd like the images to be generated in a directory `out/html/pd-images`.

**Comment by hertogp** [comment]
Looked into it, but can't seem to find a way to detect the intended output filename pandoc was asked to create.  A new option im_dir might be what you need.  You can set it to an absolute path to a topdir or relative (to current working dir for Imagine).  It will then tack on "-images" and create the directory to store the intermediate files (if any) and the images.

**Comment by hertogp** [comment]
Could you check if 0.1.6's im_dir option suits your needs?

**Comment by npryce** [comment]
That will fix it

**Comment by hertogp** [comment]
ok, thanks.
