### ISSUE TITLE
wandering if shebang could run under windows?

### ISSUE THREAD

**Issue by lavaner** [hertogp/imagine#8]
I try a codeblock like this

```
~~~ {.shebang im_out="fcb,img"}
#! python3

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 1, 1000)
plt.plot(x, np.sin(2*np.pi*x))
~~~
```

and i got a error code WinError 193.

so, it's any possible to support matplotlib under windows ?

**Comment by hertogp** [comment]
Doesn't look like it, although windows10 seems to support it (or almost)
